# Numpy - Array Manipulation

In [1]:
import numpy as np

In [2]:
arr= np.random.randint(1,10 , (3,4)) 

In [3]:
arr

array([[6, 3, 9, 2],
       [1, 6, 9, 8],
       [3, 1, 5, 7]])

In [4]:
arr.reshape(6,2)

array([[6, 3],
       [9, 2],
       [1, 6],
       [9, 8],
       [3, 1],
       [5, 7]])

In [5]:
arr.reshape(2,6)

array([[6, 3, 9, 2, 1, 6],
       [9, 8, 3, 1, 5, 7]])

In [6]:
arr

array([[6, 3, 9, 2],
       [1, 6, 9, 8],
       [3, 1, 5, 7]])

In [7]:
arr.T

array([[6, 1, 3],
       [3, 6, 1],
       [9, 9, 5],
       [2, 8, 7]])

In [8]:
arr.flatten()

array([6, 3, 9, 2, 1, 6, 9, 8, 3, 1, 5, 7])

In [9]:
arr1 = np.array([1,2,3,4,4])

In [10]:
arr1.ndim

1

In [11]:
np.expand_dims(arr1 , axis = 1)

array([[1],
       [2],
       [3],
       [4],
       [4]])

In [12]:
np.expand_dims(arr1 , axis = 0)

array([[1, 2, 3, 4, 4]])

In [13]:
arr

array([[6, 3, 9, 2],
       [1, 6, 9, 8],
       [3, 1, 5, 7]])

In [14]:
np.squeeze(arr)

array([[6, 3, 9, 2],
       [1, 6, 9, 8],
       [3, 1, 5, 7]])

In [15]:
data = np.array([[1],[2],[3]])

In [16]:
np.squeeze(data)

array([1, 2, 3])

In [17]:
arr1

array([1, 2, 3, 4, 4])

In [18]:
np.repeat(arr1, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3, 4, 4, 4, 4, 4, 4])

In [19]:
np.roll(arr1 , 2)

array([4, 4, 1, 2, 3])

In [20]:
np.diag(arr1)

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 4]])

# Numpy - Binary Operators

In [21]:
arr1 = np.random.randint(1,10, (3,4))

In [22]:
arr2 = np.random.randint(1,10, (3,4))

In [23]:
arr1

array([[1, 3, 8, 6],
       [6, 6, 9, 8],
       [4, 9, 2, 6]])

In [24]:
arr2

array([[5, 6, 2, 3],
       [2, 2, 5, 6],
       [1, 8, 9, 4]])

In [25]:
arr1+arr2

array([[ 6,  9, 10,  9],
       [ 8,  8, 14, 14],
       [ 5, 17, 11, 10]])

In [26]:
arr1*arr2

array([[ 5, 18, 16, 18],
       [12, 12, 45, 48],
       [ 4, 72, 18, 24]])

In [27]:
arr1/arr2

array([[0.2       , 0.5       , 4.        , 2.        ],
       [3.        , 3.        , 1.8       , 1.33333333],
       [4.        , 1.125     , 0.22222222, 1.5       ]])

In [28]:
arr1-arr2

array([[-4, -3,  6,  3],
       [ 4,  4,  4,  2],
       [ 3,  1, -7,  2]])

In [30]:
#remainder operation
arr1%arr2

array([[1, 3, 0, 0],
       [0, 0, 4, 2],
       [0, 1, 2, 2]])

In [31]:
arr1 ** arr2

array([[       1,      729,       64,      216],
       [      36,       36,    59049,   262144],
       [       4, 43046721,      512,     1296]])

In [32]:
arr1 & arr2

array([[1, 2, 0, 2],
       [2, 2, 1, 0],
       [0, 8, 0, 4]])

In [33]:
arr1

array([[1, 3, 8, 6],
       [6, 6, 9, 8],
       [4, 9, 2, 6]])

In [34]:
arr2

array([[5, 6, 2, 3],
       [2, 2, 5, 6],
       [1, 8, 9, 4]])

In [35]:
-arr1

array([[-1, -3, -8, -6],
       [-6, -6, -9, -8],
       [-4, -9, -2, -6]])

In [36]:
arr1|arr2

array([[ 5,  7, 10,  7],
       [ 6,  6, 13, 14],
       [ 5,  9, 11,  6]])

In [37]:
arr1>arr2

array([[False, False,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

# Numpy - String Function 

In [39]:
arr = np.array(['sarfraj','sheikh'])

In [40]:
arr

array(['sarfraj', 'sheikh'], dtype='<U7')

In [41]:
np.char.upper(arr)

array(['SARFRAJ', 'SHEIKH'], dtype='<U7')

In [42]:
np.char.title(arr)

array(['Sarfraj', 'Sheikh'], dtype='<U7')

In [43]:
np.char.capitalize(arr)

array(['Sarfraj', 'Sheikh'], dtype='<U7')

# Numpy - Mathematical Function

In [44]:
arr1

array([[1, 3, 8, 6],
       [6, 6, 9, 8],
       [4, 9, 2, 6]])

In [45]:
np.sin(arr1)

array([[ 0.84147098,  0.14112001,  0.98935825, -0.2794155 ],
       [-0.2794155 , -0.2794155 ,  0.41211849,  0.98935825],
       [-0.7568025 ,  0.41211849,  0.90929743, -0.2794155 ]])

In [46]:
np.cos(arr1)

array([[ 0.54030231, -0.9899925 , -0.14550003,  0.96017029],
       [ 0.96017029,  0.96017029, -0.91113026, -0.14550003],
       [-0.65364362, -0.91113026, -0.41614684,  0.96017029]])

In [47]:
np.tan(arr1)

array([[ 1.55740772, -0.14254654, -6.79971146, -0.29100619],
       [-0.29100619, -0.29100619, -0.45231566, -6.79971146],
       [ 1.15782128, -0.45231566, -2.18503986, -0.29100619]])

In [48]:
np.tanh(arr1)

array([[0.76159416, 0.99505475, 0.99999977, 0.99998771],
       [0.99998771, 0.99998771, 0.99999997, 0.99999977],
       [0.9993293 , 0.99999997, 0.96402758, 0.99998771]])

In [49]:
np.log10(arr1)

array([[0.        , 0.47712125, 0.90308999, 0.77815125],
       [0.77815125, 0.77815125, 0.95424251, 0.90308999],
       [0.60205999, 0.95424251, 0.30103   , 0.77815125]])

In [50]:
np.exp(arr1)

array([[2.71828183e+00, 2.00855369e+01, 2.98095799e+03, 4.03428793e+02],
       [4.03428793e+02, 4.03428793e+02, 8.10308393e+03, 2.98095799e+03],
       [5.45981500e+01, 8.10308393e+03, 7.38905610e+00, 4.03428793e+02]])

In [51]:
np.sqrt(arr1)

array([[1.        , 1.73205081, 2.82842712, 2.44948974],
       [2.44948974, 2.44948974, 3.        , 2.82842712],
       [2.        , 3.        , 1.41421356, 2.44948974]])

In [53]:
np.power(arr1,2)

array([[ 1,  9, 64, 36],
       [36, 36, 81, 64],
       [16, 81,  4, 36]])

In [54]:
np.mean(arr1)

5.666666666666667

In [56]:
np.median(arr1)

6.0

In [57]:
np.std(arr1)

2.5603819159562025

In [59]:
np.var(arr1)

6.5555555555555545

In [60]:
np.min(arr1)

1

In [61]:
np.max(arr1)

9