In [1]:
import numpy as np 

In [2]:
l = [1,2,3,4]

In [4]:
ar = np.array(l)

In [7]:
ar

array([1, 2, 3, 4])

In [5]:
type(ar)

numpy.ndarray

In [6]:
np.array([[1,2],[3,4]])

array([[1, 2],
       [3, 4]])

In [8]:
np.asarray(l)

array([1, 2, 3, 4])

In [9]:
a = [2,3,4]

In [11]:
np.asanyarray(a)

array([2, 3, 4])

In [12]:
b = np.matrix(l)

In [13]:
b

matrix([[1, 2, 3, 4]])

In [14]:
np.asanyarray(b)

matrix([[1, 2, 3, 4]])

In [15]:
a = np.array(l)

In [16]:
a

array([1, 2, 3, 4])

In [17]:
c = a

In [18]:
c

array([1, 2, 3, 4])

In [19]:
a

array([1, 2, 3, 4])

In [21]:
c[0] = 100

In [22]:
c

array([100,   2,   3,   4])

In [23]:
a

array([100,   2,   3,   4])

In [24]:
d = np.copy(a)

In [25]:
d

array([100,   2,   3,   4])

In [26]:
a

array([100,   2,   3,   4])

In [27]:
a[1] = 400

In [28]:
a

array([100, 400,   3,   4])

In [29]:
d

array([100,   2,   3,   4])

In [30]:
np.fromfunction(lambda i, j : i==j, (3,3))

array([[ True, False, False],
       [False,  True, False],
       [False, False,  True]])

In [31]:
np.fromfunction(lambda i, j : i*j, (3,3))

array([[0., 0., 0.],
       [0., 1., 2.],
       [0., 2., 4.]])

In [33]:
iterable = (i*i for i in range(5))

In [34]:
np.fromiter(iterable, float)

array([ 0.,  1.,  4.,  9., 16.])

In [35]:
np.fromstring('234 234' , sep= ' ')

array([234., 234.])

In [36]:
np.fromstring('4,5' , sep= ',')

array([4., 5.])

# NumPy - Data Type

In [37]:
l = [2,3,4,5,6]

In [38]:
ar = np.array(l)

In [39]:
ar

array([2, 3, 4, 5, 6])

In [40]:
ar.ndim

1

In [41]:
ar2 = np.array([[1,2,3,4], [2,3,4,5]])

In [42]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [43]:
ar2.ndim 

2

In [44]:
ar.size

5

In [45]:
ar2.size

8

In [46]:
ar

array([2, 3, 4, 5, 6])

In [47]:
ar2

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [48]:
ar.shape

(5,)

In [49]:
ar2.shape

(2, 4)

In [51]:
ar.dtype

dtype('int64')

In [52]:
ar2.dtype

dtype('int64')

In [53]:
ar22 = np.array([(1.2,45,45),(23,45,66)])

In [54]:
ar22

array([[ 1.2, 45. , 45. ],
       [23. , 45. , 66. ]])

In [55]:
ar22.dtype

dtype('float64')

In [57]:
list(range(5))

[0, 1, 2, 3, 4]

In [58]:
list(range(0.1 , 5))

TypeError: 'float' object cannot be interpreted as an integer

In [59]:
np.arange(2.3,5.6)

array([2.3, 3.3, 4.3, 5.3])

In [61]:
list(np.arange(2.3,5.6, .3))

[2.3,
 2.5999999999999996,
 2.8999999999999995,
 3.1999999999999993,
 3.499999999999999,
 3.799999999999999,
 4.099999999999999,
 4.399999999999999,
 4.699999999999998,
 4.999999999999998,
 5.299999999999998]

In [62]:
np.linspace(1,5,10)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [63]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [64]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [65]:
np.zeros((3,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [66]:
np.ones(4)

array([1., 1., 1., 1.])

In [68]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [70]:
on = np.ones((2,3,2))

In [72]:
on + 5

array([[[6., 6.],
        [6., 6.],
        [6., 6.]],

       [[6., 6.],
        [6., 6.],
        [6., 6.]]])

In [73]:
on*4

array([[[4., 4.],
        [4., 4.],
        [4., 4.]],

       [[4., 4.],
        [4., 4.],
        [4., 4.]]])

In [75]:
np.empty((3,6))

array([[0., 0., 0., 1., 1., 1.],
       [2., 2., 2., 0., 1., 2.],
       [0., 1., 2., 0., 1., 2.]])

In [76]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [77]:
np.linspace(2,4, 20)

array([2.        , 2.10526316, 2.21052632, 2.31578947, 2.42105263,
       2.52631579, 2.63157895, 2.73684211, 2.84210526, 2.94736842,
       3.05263158, 3.15789474, 3.26315789, 3.36842105, 3.47368421,
       3.57894737, 3.68421053, 3.78947368, 3.89473684, 4.        ])

In [79]:
np.logspace(2,5, 10 , base = 2)

array([ 4.        ,  5.0396842 ,  6.34960421,  8.        , 10.0793684 ,
       12.69920842, 16.        , 20.1587368 , 25.39841683, 32.        ])

In [81]:
arr = np.random.randn(3,4)

In [82]:
import pandas as pd

In [83]:
pd.DataFrame(arr)

0         1         2         3
0  0.148674  0.653127  0.736094  0.456869
1  0.320317  1.155428 -0.496118  0.164955
2 -1.238660  0.071454 -0.685603 -0.222770

In [84]:
np.random.rand(3,4)

array([[0.77792119, 0.69576451, 0.02302517, 0.03689385],
       [0.05080768, 0.7240982 , 0.34232317, 0.95436638],
       [0.71537383, 0.72861532, 0.17397185, 0.30862372]])

In [88]:
pd.DataFrame(np.random.randint(1,110,(300,400))).to_csv('test5.csv')

In [89]:
arr = np.random.rand(3,4)

In [90]:
arr

array([[0.93397348, 0.35095858, 0.40003369, 0.546341  ],
       [0.2524981 , 0.44878562, 0.07529018, 0.32539592],
       [0.23116377, 0.62917995, 0.73338324, 0.65106344]])

In [93]:
arr1 = arr.reshape(6,2)

In [94]:
arr1

array([[0.93397348, 0.35095858],
       [0.40003369, 0.546341  ],
       [0.2524981 , 0.44878562],
       [0.07529018, 0.32539592],
       [0.23116377, 0.62917995],
       [0.73338324, 0.65106344]])

In [95]:
arr1[1,1]

0.5463409960413319

In [98]:
arr1[2:5,1]

array([0.44878562, 0.32539592, 0.62917995])

In [105]:
arr = np.random.randint(1,100 , (5,5))

In [107]:
arr

array([[66, 29, 95, 65, 38],
       [36, 88, 14, 76, 94],
       [ 7, 80, 64, 21, 39],
       [41, 91, 59, 25, 67],
       [21, 76, 61, 58, 59]])

In [109]:
arr[arr>50]

array([66, 95, 65, 88, 76, 94, 80, 64, 91, 59, 67, 76, 61, 58, 59])

In [110]:
arr

array([[66, 29, 95, 65, 38],
       [36, 88, 14, 76, 94],
       [ 7, 80, 64, 21, 39],
       [41, 91, 59, 25, 67],
       [21, 76, 61, 58, 59]])

In [111]:
arr[2:4,[1,2]]

array([[80, 64],
       [91, 59]])

In [113]:
arr[0,0] = 5000

In [114]:
arr

array([[5000,   29,   95,   65,   38],
       [  36,   88,   14,   76,   94],
       [   7,   80,   64,   21,   39],
       [  41,   91,   59,   25,   67],
       [  21,   76,   61,   58,   59]])

In [116]:
arr1 = np.random.randint(1,3 , (3,3))
arr2 = np.random.randint(1,3 , (3,3))

In [117]:
arr1

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [118]:
arr2

array([[1, 2, 2],
       [2, 1, 1],
       [2, 1, 2]])

In [119]:
arr1+arr2

array([[3, 3, 4],
       [4, 2, 3],
       [4, 3, 3]])

In [122]:
arr1-arr2

array([[ 1, -1,  0],
       [ 0,  0,  1],
       [ 0,  1, -1]])

In [123]:
arr1/arr2

array([[2. , 0.5, 1. ],
       [1. , 1. , 2. ],
       [1. , 2. , 0.5]])

In [124]:
arr1*arr2

array([[2, 2, 4],
       [4, 1, 2],
       [4, 2, 2]])

In [125]:
arr1

array([[2, 1, 2],
       [2, 1, 2],
       [2, 2, 1]])

In [126]:
arr2

array([[1, 2, 2],
       [2, 1, 1],
       [2, 1, 2]])

In [127]:
arr1@arr2

array([[8, 7, 9],
       [8, 7, 9],
       [8, 7, 8]])

In [128]:
arr1/0

/tmp/ipykernel_160/1510032488.py:1: RuntimeWarning: divide by zero encountered in divide
  arr1/0


array([[inf, inf, inf],
       [inf, inf, inf],
       [inf, inf, inf]])

In [129]:
arr1+100

array([[102, 101, 102],
       [102, 101, 102],
       [102, 102, 101]])

In [130]:
arr1**2

array([[4, 1, 4],
       [4, 1, 4],
       [4, 4, 1]])

# NumPy - Broadcasting

In [131]:
arr = np.zeros((4,4))

In [132]:
arr

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
row = np.array([1,2,3,4])

In [134]:
row

array([1, 2, 3, 4])

In [135]:
arr+row

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [136]:
row.T

array([1, 2, 3, 4])

In [137]:
col = np.array([[1,2,3,4]])

In [138]:
col.T

array([[1],
       [2],
       [3],
       [4]])

In [139]:
col

array([[1, 2, 3, 4]])

In [141]:
arr+col.T

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.]])

In [143]:
arr1 = np.random.randint(1,4,(3,4))

In [144]:
arr1

array([[3, 3, 2, 1],
       [1, 3, 2, 3],
       [1, 3, 3, 2]])

In [145]:
np.sqrt(arr1)

array([[1.73205081, 1.73205081, 1.41421356, 1.        ],
       [1.        , 1.73205081, 1.41421356, 1.73205081],
       [1.        , 1.73205081, 1.73205081, 1.41421356]])

In [146]:
np.exp(arr1)

array([[20.08553692, 20.08553692,  7.3890561 ,  2.71828183],
       [ 2.71828183, 20.08553692,  7.3890561 , 20.08553692],
       [ 2.71828183, 20.08553692, 20.08553692,  7.3890561 ]])

In [147]:
np.log10(arr1)

array([[0.47712125, 0.47712125, 0.30103   , 0.        ],
       [0.        , 0.47712125, 0.30103   , 0.47712125],
       [0.        , 0.47712125, 0.47712125, 0.30103   ]])

In [ ]:
np.random.ran