# Sort , Search , & Counting Function. 

In [1]:
import numpy as np

In [2]:
arr = np.array([4,3,4,5,6,7,65,87,566,7,8,9])

In [3]:
arr

array([  4,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

In [4]:
arr

array([  4,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

In [5]:
np.sort(arr)

array([  3,   4,   4,   5,   6,   7,   7,   8,   9,  65,  87, 566])

In [8]:
np.searchsorted(arr , 10)

6

In [9]:
arr1 = np.array([0,345,454,0,0,0,0,0])

In [10]:
np.count_nonzero(arr1)

2

In [11]:
arr

array([  4,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

In [13]:
np.where(arr>15)

(array([6, 7, 8]),)

In [15]:
np.extract(arr >6 , arr)

array([  7,  65,  87, 566,   7,   8,   9])

# Numpy - Byte Swapping

In [17]:
arr

array([  4,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

In [18]:
arr.byteswap()

array([ 288230376151711744,  216172782113783808,  288230376151711744,
        360287970189639680,  432345564227567616,  504403158265495552,
       4683743612465315840, 6269010681299730432, 3891673028001529856,
        504403158265495552,  576460752303423488,  648518346341351424])

# Numpy - Copies & Views

In [19]:
arr

array([  4,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

In [20]:
a = np.copy(arr)

In [21]:
b = arr.view()

In [22]:
b

array([  4,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

In [23]:
arr

array([  4,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

In [24]:
b[0] = 67

In [25]:
b

array([ 67,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

In [26]:
arr

array([ 67,   3,   4,   5,   6,   7,  65,  87, 566,   7,   8,   9])

# Numpy - Matrix Library

In [27]:
import numpy.matlib as nm

In [28]:
nm.zeros(5)

matrix([[0., 0., 0., 0., 0.]])

In [29]:
nm.ones((3,4))

matrix([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [30]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

# Numpy - Linear Algebra

In [31]:
arr1 = np.random.randint([[2,3] , [4,5]])

In [32]:
arr2 =  np.random.randint([[5,3] , [2,5]])

In [33]:
np.dot(arr1,arr2)

array([[6, 4],
       [8, 8]])

In [34]:
arr1@arr2

array([[6, 4],
       [8, 8]])